openapi: 3.0.0
components:
  schemas:
    # Common response schema definitions
    PaginatedResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            type: object
        count:
          type: integer
          description: Number of items in the current page
          example: 10
        totalCount:
          type: integer
          description: Total number of items across all pages
          example: 50
        currentPage:
          type: integer
          example: 1
        totalPages: 
          type: integer
          example: 5
        message:
          type: string
          nullable: true
          
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: "Đã xảy ra lỗi khi xử lý yêu cầu"
        error:
          type: object
          nullable: true
          properties:
            code:
              type: integer
            details:
              type: string
              
    # User schema definition
    User:
      type: object
      properties:
        id:
          type: string
          example: "60d21b4667d0d8992e610c85"
        fullName:
          type: string
          example: "Nguyễn Văn A"
        username:
          type: string
          example: "nguyenvana"
        role:
          type: string
          enum: [admin, manager, user]
          example: "manager"
        unit:
          type: object
          properties:
            id:
              type: string
              example: "60d21b4667d0d8992e610c80"
            name:
              type: string
              example: "Đại đội 1"
        rank:
          type: string
          example: "Thiếu úy"
        position:
          type: string
          example: "Đội trưởng"
        status:
          type: string
          enum: [active, inactive]
          example: "active"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          
    # Supply schema definition
    Supply:
      type: object
      properties:
        id:
          type: string
          example: "60d21b4667d0d8992e610c86"
        unit:
          type: object
          properties:
            id:
              type: string
              example: "60d21b4667d0d8992e610c80"
            name:
              type: string
              example: "Đại đội 1"
        category:
          type: object
          properties:
            id:
              type: string
              example: "60d21b4667d0d8992e610c82"
            name:
              type: string
              example: "Rau củ"
        product:
          type: object
          properties:
            id:
              type: string
              example: "60d21b4667d0d8992e610c83"
            name:
              type: string
              example: "Cà rốt"
        quantity:
          type: number
          example: 100
        harvestDate:
          type: string
          format: date
          example: "2023-01-15"
        stationEntryDate:
          type: string
          format: date
          nullable: true
        receivedQuantity:
          type: number
          nullable: true
        status:
          type: string
          enum: [pending, approved, rejected, completed]
          example: "pending"
        note:
          type: string
          example: "Hàng tươi mới"
        createdBy:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
        approvedBy:
          type: object
          nullable: true
          properties:
            id:
              type: string
            name:
              type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time