version: '3.8'

services:
  # MongoDB Database
  db:
    image: mongo:latest
    container_name: military_logistics_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: military-logistics
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - military-logistics-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: military_logistics_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@db:27017/military-logistics?authSource=admin
      - JWT_SECRET=your-jwt-secret-key
      - PORT=5000
    depends_on:
      - db
    networks:
      - military-logistics-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: military_logistics_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - military-logistics-network
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongo_data:

networks:
  military-logistics-network:
    driver: bridge
