openapi: 3.0.0
info:
  title: Military Logistics API
  description: API for the Military Logistics System
  version: 1.0.0
  contact:
    name: Development Team
servers:
  - url: http://localhost:5001/api
    description: Development server
  - url: https://api.military-logistics.com/api
    description: Production server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths: {}

tags:
  - name: Auth
    description: Authentication endpoints
  - name: Users
    description: User management endpoints
  - name: Units
    description: Unit management endpoints
  - name: Products
    description: Product management endpoints
  - name: Categories
    description: Category management endpoints
  - name: Supplies
    description: Supply management endpoints
  - name: Reports
    description: Report generation endpoints
  - name: Statistics
    description: System statistics endpoints
  - name: Notifications
    description: Notification endpoints
  - name: Roles
    description: Role management endpoints
  - name: Print
    description: Document printing endpoints 